name: Check README

on:
  push:
    branches:
      - main # rama principal

jobs:
  verificar-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Instalar Markdown linter
        run: npm install -g markdownlint-cli

      - name: Check README
        run: markdownlint --config .markdownlint.yml README.md
